name: Deploy to Goggle App Engine (GAE)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - id: generate_dotenv_file
        env:
          MY_DOTENV: ${{ secrets.MY_DOTENV }}
        run: echo "$MY_DOTENV" > .env-for-app-yaml
  
      - id: prepare-app-yaml
        uses: mshick/fast-envsubst@v1
        with:
          env-file: .env-for-app-yaml
          in-file: app.yaml.template
          out-file: app.yaml

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next Project
        run: npm run build

      - name: Google Cloud Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Deploy to Google App Engine
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          gcloud app deploy app.yaml --quiet